---
- name: Install apache # Nme of the whole playbook
  hosts: all # Running on all nodes
  become: true # Same as --become, run this as root
  tasks:
  - name: install apache2 package and php support # Name of the task
    apt: # Using the builtin apt module
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: true # Before installing run apt update
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install apache2 package
    dnf: # Using the builtin dnf module
      name: 
        - httpd 
        - php
      state: latest
      update_cache: true
    when: ansible_distribution == "CentOS"